### ISSUE TITLE
Exit Program Option

### ISSUE THREAD

**Issue by sick13** [lich426/FanCtrl#3]
Ok first of Thank you soo much for this awesome and debloated fan control program

Now a small request if possible about exiting the program

When i Game or do some render intensive stuff i set my profile to say "Game" i have already configured the GPU graph as i like and everything is as it should be

now if i don't set the profile back to "Normal" (i have gpu fans shut off on normal i let the gpu regulate that) and exit the program the Fan profile stays at "Game" even if the program is not running,and that means GPU fans will be running with the "Game" Profile even if i don't do any intensive stuff

reason for asking is convenience, sometimes i forget to change the profile and i just exit the program

so an option to revert to "Normal" profile if the program exits would be super useful

**Comment by lich426** [comment]
The profile is only four types of name
All settings must be set manually
When you restart the program, it is loaded to the setting when you exit

**Comment by sick13** [comment]
i understand that, but is there a way to add an option not to do that? as an example take MSI Afterburner, what ever your setting when you exit the program it sets everything to default, that being said if it's too much hassle it's fine as it is, just for the sake of convenience it would be easier

**Comment by lich426** [comment]
Sorry, current setting cannot be changed because it is generally used by all users
but, you can download this project and build it after modification

Profile can be viewed in the FanCtrl/Data/Control/ControlManager.cs file.
Mode can be changed to ModeIndex. (0 : Normal, 1: Silence, 2: Performance, 3: Game)
After changing ModeIndex, you must call the write() method and save it as a file.

When you click exit of tray icon, onTrayMenuExit method in the Mainform.cs file is called.
In the onTrayMenuExit method, you can change the mode to Normal-type before the program ends.

For example,
<pre><code>private void onTrayMenuExit(object sender, EventArgs e)
{
	if (mControlForm != null)
	{
		mControlForm.Close();
		mControlForm = null;
	}

	HardwareManager.getInstance().stop();

	mFanIconTimer.Stop();
	mTrayIcon.Visible = false;

	ControlManager.getInstance().ModeIndex = 0;    // Normal type
	ControlManager.getInstance().write();          // Save to file

	mIsExit = true;
	Application.ExitThread();
	Application.Exit();
}
</code></pre>

**Comment by sick13** [comment]
Thank you for the info but this is all black magic to me :D (don't know a single thing about coding) so all i ask please consider adding this option in the future :) thanks for taking the time to look into this
